import React from "react";
import {useQuery,useMutation} from "@tanstack/react-query";
import {api} from "../lib/api";
import {useBrands} from "../lib/rag";
import {Button,Input,PageHeader} from "../components";
import "./brands.css";
const money=(n:number)=>`$${(n/1000000).toFixed(4)}`;

export function RagOperationsPage(){
 const report=useQuery({queryKey:["rag-usage"],queryFn:()=>api.get<any>("/api/rag/usage"),refetchInterval:10000});
 const [limit,setLimit]=React.useState("");
 const budget=useMutation({mutationFn:()=>api.post("/api/rag/budget",{monthlyLimitMicros:limit===""?null:Math.round(Number(limit)*1000000)}),onSuccess:()=>void report.refetch()});
 const [price,setPrice]=React.useState({provider:"ANTHROPIC",model:"",operation:"*",inputPerMillion:0,outputPerMillion:0,cacheReadPerMillion:0,cacheWritePerMillion:0,unitMicros:0,version:""});
 const pricing=useMutation({mutationFn:()=>api.post("/api/rag/prices",price),onSuccess:()=>void report.refetch()});
 return <div className="route-view"><PageHeader title="Usage and budgets" subtitle="Measure provider work, version your rates, and control workspace spending."/>
 {report.error&&<p role="alert">{report.error.message}</p>}
 {report.data&&<section className="rag-panel"><div className="rag-stats"><div><strong>{money(report.data.actualMicros)}</strong><span>Priced usage this month</span></div><div><strong>{money(report.data.reservedMicros)}</strong><span>Reserved or uncertain</span></div><div><strong>{report.data.unpricedCalls}</strong><span>Calls without a complete price</span></div></div><p>Costs use your versioned rates, not provider invoices. Unknown calls remain visible; failed requests retain reservations because they may have been billed.</p><p>Current monthly cap: {report.data.budget?.monthlyLimitMicros==null?"not set":money(report.data.budget.monthlyLimitMicros)}. Active prompt model: {report.data.routing?.value?.model||"configured default"}.</p></section>}
 <section className="rag-panel"><h2>Monthly workspace budget</h2><form className="rag-actions" onSubmit={e=>{e.preventDefault();budget.mutate();}}><label>USD cap (blank to disable)<Input type="number" min="0" max="2000" step="0.01" value={limit} onChange={e=>setLimit(e.target.value)}/></label><Button type="submit" loading={budget.isPending}>Save cap</Button></form><p>When a cap is enabled, unpriced provider operations are blocked. Reservations use conservative token bounds and configurable per-unit rates.</p>{budget.error&&<p role="alert">{budget.error.message}</p>}</section>
 <section className="rag-panel"><h2>Add a pricing version</h2><p>Use the exact model ID and current contracted rates. Token rates are USD per million; per-unit rates are microdollars (one million = $1). For video, one unit is one rendered second. Mixed image/text response pricing should use conservative rates until reconciled with billing.</p><form onSubmit={e=>{e.preventDefault();pricing.mutate();}} className="rag-form-grid"><label>Provider<select className="control" value={price.provider} onChange={e=>setPrice({...price,provider:e.target.value})}>{["ANTHROPIC","OPENAI","KLING","RUNWAY"].map(v=><option key={v}>{v}</option>)}</select></label>{["model","operation","version"].map(k=><label key={k}>{k}<Input required value={(price as any)[k]} onChange={e=>setPrice({...price,[k]:e.target.value})}/></label>)}{["inputPerMillion","outputPerMillion","cacheReadPerMillion","cacheWritePerMillion","unitMicros"].map(k=><label key={k}>{k}<Input type="number" min="0" step="0.01" value={(price as any)[k]} onChange={e=>setPrice({...price,[k]:Number(e.target.value)})}/></label>)}<Button type="submit" loading={pricing.isPending}>Save immutable price</Button></form>{pricing.error&&<p role="alert">{pricing.error.message}</p>}</section>
 <section className="rag-panel"><h2>Recent operations</h2><div className="rag-table-wrap"><table><thead><tr><th>Operation</th><th>Model</th><th>Status</th><th>Input / output</th><th>Cache read / write</th><th>Price version</th><th>Cost</th></tr></thead><tbody>{report.data?.records.map((r:any)=><tr key={r.id}><td>{r.operation}</td><td>{r.model}</td><td>{r.status}</td><td>{r.inputTokens} / {r.outputTokens}</td><td>{r.cacheReadTokens} / {r.cacheWriteTokens}</td><td>{r.priceVersion||"not configured"}</td><td>{r.costMicros==null?"unpriced / reserved":money(r.costMicros)}</td></tr>)}</tbody></table></div></section>
 </div>;
}

export function RagEvaluationsPage(){
 const brands=useBrands();const [brandId,setBrand]=React.useState(""),[name,setName]=React.useState("Brand prompt benchmark"),[model,setModel]=React.useState(""),[live,setLive]=React.useState(false),[selected,setSelected]=React.useState(""),[reveal,setReveal]=React.useState(false);
 const list=useQuery({queryKey:["rag-evaluations"],queryFn:()=>api.get<any>("/api/rag/evaluations"),refetchInterval:5000});
 const results=useQuery({queryKey:["rag-evaluation",selected,reveal],queryFn:()=>api.get<any>(`/api/rag/evaluations/${selected}?reveal=${reveal?1:0}`),enabled:!!selected,refetchInterval:5000});
 const run=useMutation({mutationFn:()=>api.post<any>("/api/rag/evaluations",{brandId,name,model:model||"mock",live}),onSuccess:r=>{setSelected(r.id);void list.refetch();}});
 const activate=useMutation({mutationFn:()=>api.post(`/api/rag/evaluations/${selected}/activate`)});
 return <div className="route-view"><PageHeader title="Prompt evaluations" subtitle="Compare 24 fixed briefs across no retrieval, keyword retrieval and hybrid retrieval."/>
 <section className="rag-panel"><h2>Run a benchmark</h2><form className="rag-form-grid" onSubmit={e=>{e.preventDefault();run.mutate();}}><label>Brand<select className="control" value={brandId} onChange={e=>setBrand(e.target.value)} required><option value="">Select brand</option>{brands.data?.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>Run name<Input value={name} onChange={e=>setName(e.target.value)} required/></label><label>Prompt model<Input value={model} onChange={e=>setModel(e.target.value)} placeholder="Exact model ID for a live run" required={live}/></label><label><input type="checkbox" checked={live} onChange={e=>setLive(e.target.checked)}/> Run 72 paid prompt calls (workspace budget applies)</label><Button type="submit" disabled={!brandId} loading={run.isPending}>{live?"Queue live benchmark":"Queue mock benchmark"}</Button></form>{run.error&&<p role="alert">{run.error.message}</p>}<p>Mock runs verify the workflow; they do not measure model quality and cannot activate a model.</p></section>
 <section className="rag-panel"><h2>Runs</h2><select className="control" value={selected} onChange={e=>{setSelected(e.target.value);setReveal(false);}}><option value="">Choose run</option>{list.data?.runs.map((r:any)=><option key={r.id} value={r.id}>{r.name} · {r.status} · {r.providerMode}</option>)}</select>{selected&&<label><input type="checkbox" checked={reveal} onChange={e=>setReveal(e.target.checked)}/> Reveal retrieval variants and usage</label>}
 {results.data&&<><p>{results.data.status} · {results.data.results.length}/72 results</p><Button loading={activate.isPending} onClick={()=>activate.mutate()}>Activate evaluated prompt model</Button><p>Activation requires a live completed run and at least 20 hybrid results with average scores of 4/5 on every dimension. Compare quality and pricing before activating a lower-cost model.</p>{activate.error&&<p role="alert">{activate.error.message}</p>}{activate.isSuccess&&<p>Model activated for new generations.</p>}{results.data.results.map((r:any)=><EvalResult key={r.id} runId={selected} result={r} brief={list.data?.cases.find((c:any)=>c.id===r.caseId)?.brief}/>)}</>}
 </section></div>;
}
function EvalResult({runId,result,brief}:{runId:string;result:any;brief?:string}){
 const [fidelity,setFidelity]=React.useState(result.humanScores?.fidelity||4),[briefAdherence,setBrief]=React.useState(result.humanScores?.briefAdherence||4),[brandFit,setBrand]=React.useState(result.humanScores?.brandFit||4);
 const save=useMutation({mutationFn:()=>api.post(`/api/rag/evaluations/${runId}/rate`,{resultId:result.id,fidelity,briefAdherence,brandFit})});
 return <details className="rag-context"><summary>{result.caseId} · sample {result.blindLabel}{result.variant?` · ${result.variant}`:""}{result.humanScores?" · reviewed":""}</summary><p><strong>Original brief:</strong> {brief||result.caseId}</p><pre>{result.prompt}</pre>{result.metrics&&<pre>{JSON.stringify(result.metrics,null,2)}</pre>}<div className="rag-form-grid">{[["Fidelity",fidelity,setFidelity],["Brief",briefAdherence,setBrief],["Brand",brandFit,setBrand]].map(([label,value,set])=><label key={String(label)}>{String(label)}<select className="control" value={value as number} onChange={e=>(set as any)(Number(e.target.value))}>{[1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select></label>)}<Button loading={save.isPending} onClick={()=>save.mutate()}>Save blind rating</Button></div>{save.error&&<p role="alert">{save.error.message}</p>}{save.isSuccess&&<p>Rating saved</p>}</details>;
}
